### ISSUE TITLE
Breaking Changes for Version 0.1.0?

### ISSUE THREAD

**Issue by soltran** [google/rejoiner#50]
Trying to upgrade from 0.0.4 to 0.1.0, but running into issues.

None of the examples work with 0.1.0 for me either when I try to upgrade. While I am able to installDist, I get this error when I pull open localhost:8080:

```<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /graphql. Reason:
<pre>    java.lang.NoClassDefFoundError: com/google/api/graphql/execution/GuavaListenableFutureSupport$1</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.8.v20160314</a><hr/>
</body>
</html>
```

Plus I get this error in the logs:

```23503 [qtp1267032364-13] WARN org.eclipse.jetty.servlet.ServletHandler - Error for /graphql
java.lang.NoClassDefFoundError: graphql/execution/instrumentation/NoOpInstrumentation
	at java.lang.ClassLoader.defineClass1(Native Method)
```

```23658 [qtp1267032364-12] WARN org.eclipse.jetty.servlet.ServletHandler - Error for /graphql
java.lang.NoClassDefFoundError: com/google/api/graphql/execution/GuavaListenableFutureSupport$1```

Would appreciate if someone can help :)

**Comment by siderakis** [comment]
Taking a look now!

**Comment by soltran** [comment]
thank you @siderakis !

**Comment by soltran** [comment]
That fixed it! Thanks!
